### ISSUE TITLE
Make the app run

### ISSUE THREAD

**Issue by cypressious** [JurrianFahner/play-with-graalvm#1]
I'm interested in getting Spark to work with graalvm. I assume the project is WIP so I'd like to see when it actually runs.

**Comment by JurrianFahner** [comment]
Well I don't have commitment or vision to spend a lot of time on my project.

However I'm very  interested in the direction  graal and graalvm are evolving. 

The idea of this project is that you can run it yourself, by using docker (see readme). However I know that running docker on windows machines can be challenge. But Docker is not required if you open the Dockerfile you see the steps I take to compile the program and create a docker image. The last command shows you how to run the binary. 

Does my response answer your question? If that's not the case, please provide me with more information.
